### ISSUE TITLE
Commercial Experience

### ISSUE THREAD

**Issue by sarahruggless** [18F/bpa-fedramp-dashboard#11]
For this first draft RFQ, you are requesting 2 project examples similar to the scope for the FedRAMP dashboard. This requires links to the Git repository and to the live site (or screenshots). If we have similar experience to this scope from commercial clients, they most likely will not allow us to provide the Git repository or source code or even screenshots of their systems. Is there another way to use the commercial experience as a reference? Can we provide a case study and a client point of contact for the project for verification? Do you envision most of the BPA task orders having this type of similar experience qualification?

**Comment by brianfunk** [comment]
For Similar Experience, Section 7.d of the RFQ asks for links to the public Git repository that includes the source code that was developed and accepted for the project, live links of the final product or current staging environment, or screenshots. Not all similar experiences will have publicly available Git repositories. Is this a requirement of a Similar Experience? Can screenshots of private repos substitute for links?

**Comment by jposi** [comment]
18F has a strong preference for "showing, not telling" and "working in the open." Because this particular requirement is for a public-facing dashboard, 18F will require an actual demonstrable of similar experience, and a client point of contact or case study will not be considered sufficient. On the second question, it is premature for 18F to predict whether whether future BPA orders will have this type of qualification.

@brianfunk We will get back to you about the question on the private repo.

**Comment by randyhart** [comment]
As previously indicated, 18F feels that similar experience is best demonstrated when the evaluation team can review the actual repo or work that was produced.  

For the similar experience evaluation factor - Actual access to a publicly available Git repository is considered more responsive than screenshots of private repos.  However, this is not a "pass/fail" requirement - if an offeror only has screenshots as evidence of their similar experience, they can still participate as part of this procurement.

The RFQ letter will be revised as needed to reflect this response.
