### ISSUE TITLE
FSS 70 contract activity

### ISSUE THREAD

**Issue by patrickmcconnell** [18F/bpa-fedramp-dashboard#16]
In the 18F Agile Blanket Purchase Agreement Ordering Guide, it is noted that "all awardees must have valid Federal Supply Schedule (FSS) 70 contracts."  Could you provide guidance to BPA holders on whether it is sufficient to actively bid on the Agile BPA to maintain a Schedule 70 contract, or must we be active on both vehicles?

**Comment by randyhart** [comment]
Pursuant to Section 5.0 of the Agile BPA, the BPA expires 5 years from date of award or at the end of the Multiple Award Schedule contract period, whichever is earlier. Therefore, all BPA awardees must have a valid FSS 70 contract in order to maintain their BPA. Please consult with the Procuring Contracting Officer of your FSS 70 contract regarding guidance about maintaining your FSS 70 contract.
