### ISSUE TITLE
Labor categories

### ISSUE THREAD

**Issue by patrickmcconnell** [18F/bpa-fedramp-dashboard#23]
In the Performance Work Statement, the government requests "At a minimum, a Project Manager must be identified and designated as Key Personnel."  It would greatly facilitate our response if the government utilizes the Agile BPA labor categories; or, at minimum, provides an equivalency table.  I am guessing that each time we see a role name or labor category that doesn't match up, we would end up asking about it anyway so that we are on the same page with the government as to resourcing and pricing.

**Comment by davecassidytcg** [comment]
Great suggestion. It might be better, however, to state explicitly what the experience, education, and other requirements might be for the roles in question (rather than 18F dictating the labor categories to bid, which would limit offeror flexibility). This is already done somewhat for this RFQ in 5.7.2.f but could be elaborated if more specific requirements are known or desired. That said, if 18F knows for sure what labor category bidders should employ, it'd definitely help to remove the mystery from this part of the bid process.

**Comment by jposi** [comment]
The correct labor category in the PWS should be "Product Manager or "Delivery Manager".  Vendors' proposed labor categories shall be consistent with the awarded labor categories of the BPA.
