### ISSUE TITLE
Oral Presentation

### ISSUE THREAD

**Issue by JeffreyDanforth** [18F/bpa-fedramp-dashboard#42]
For the first project, key personnel are required to attend the Oral Presentation.  Will this be a typical requirement of all future 18F submissions?

**Comment by brianfunk** [comment]
The Instructions for Oral Presentations states “The contractor may include as many participants as it feels is necessary...Type and number of participants included is at the contractor’s discretion and is the full responsibility of the contractor.” But then it also states ”All proposed Key Personnel currently employed by the Offeror or its teaming partners shall attend the session”. Furthermore, the RFQ states that all proposed staff shall be identified as key personnel. Does this mean that the entire team must attend the orals since all staff are considered key (per the RFQ)? Or can we decide who and how many participants attend as stated in the oral presentations instructions?

**Comment by jposi** [comment]
While we plan to use oral presentations we are going to use our experiences with this first order to inform future approaches to RFQs.

@brianfunk Please see [issue 20](https://github.com/18F/bpa-fedramp-dashboard/issues/20) for an answer to your comment on this issue.
