### ISSUE TITLE
Bash command

### ISSUE THREAD

**Issue by fmorelli** [18F/bpa-fedramp-dashboard#62]
Section 4.0, Requirements of the PWS has a requirement to deploy through a single bash command. Can you expound on what you expect that bash script to specifically do?

**Comment by patrickmcconnell** [comment]
I have been reading through the questions, and they are all very good questions.  It occurs to me that part of the challenge 18F is dealing with is not overspecifying the solution up front because that would greatly limit the effectiveness of the Agile process.  However, as vendors, we are presented with a fixed price contract, meaning we must implement the full solution to the full satisfaction of the government within the cost we propose.  We have found Agile requirements elicitation to be very challenging in a fixed price environment.  

Would changing the contract to T&M allow the government flexibility in the amount of pre-RFQ requirements gathering and design specification needed so that vendors can fulfill that role in an Agile manner?  T&M also fosters a collaborative, shared risk environment between the contractor and the government rather than putting all of the risk of delivery for underspecified systems on the contractor.

**Comment by inQbationLabs** [comment]
Agree with @patrickmcconnell that Pre-Fixed price + Pre-Fixed requirements does not = Agile.

We believe that if one project management variable is fixed, i.e., Price then the other project management variables need to be fluid or flexible.  That is how we define agile.  Besides, the whole concept of waterfall is the assumption that all the requirements are known and documented up front, which we all know is a fallacy.  Agile presumes that we don't have perfect God-like knowledge of what needs to be done and that requirements will evolve over time.

So, if there is a fixed budget that we have to stick to, no problem, but there will need to be some flexibility with regard to scope of work and acceptance standards down the road because you can't have it both ways.

**Comment by jposi** [comment]
Hi all - my response here is to @fmorelli 's original issue: The intention of the bash script is to enable the generation of a static site, inclusive of any necessary build steps (pre-processing, minimization, etc).

We are also pleased with the quality of the questions. 

We discussed FFP vs T&M on the call today. We can continue this discussion in a new issue if @inQbationLabs or @patrickmcconnell wants to continue it.
