### ISSUE TITLE
Warranty - questions and feedback

### ISSUE THREAD

**Issue by adamjhorvath** [18F/bpa-fedramp-dashboard#68]
Is it the intention of the government for the Contractor’s warranty of services to extend until the end of the acceptance of final deliverables, which shall be no later than 30 days following the end of the period of performance, and after such 30 day period the warranty is no longer required?  We kindly request that this warranty period be clarified both in the pre-solicitation question and answers and in the resulting RFQ and TO award.    

Also, the current BPA warranty terms state:  “The contractor shall be responsible for reworking any failed physical components at the contractor’s expenses.  Additional warranty terms may be incorporated into individual task orders.”  This warranty provision does NOT define the warranty period, disclaim liability associated with third party software, services, changes in environment, requirements, or modifications made by the govt or third parties.  There are no warranty provisions in the current TO.  In the TO under Inspection and Acceptance FAR 52.246-4 is incorporated.  This FAR provision states that if services do not conform with contract requirements and defects in services cannot be corrected by contractor, the govt can reduce the contract price to reflect the reduced value of services performed, terminate the contract for default, or the govt can charge to us any cost incurred by the govt directly related to performance of such services that the vendor cannot perform. However, as the TO is currently written many elements of the warranty terms would be missing from the award and would create risk and ambiguity for any vendor involved.

**Comment by jposi** [comment]
Per section 6.10 of the PWS, 18F intends to commit deliverables under this order to the public domain pursuant to the CC0 license. The CC0 provision states that "Affirmer offers the Work as-is and makes no representations or warranties of any kind concerning the Work, express, implied, statutory or otherwise, including without limitation warranties of title, merchantability, fitness for a particular purpose, non infringement, or the absence of latent or other defects, accuracy, or the present or absence of errors, whether or not discoverable, all to the greatest extent permissible under applicable law." Accordingly, no additional warranty provisions shall apply.
