### ISSUE TITLE
Assumptions

### ISSUE THREAD

**Issue by adamjhorvath** [18F/bpa-fedramp-dashboard#71]
It is very common for information requested to not be perfectly clear or subject to multiple interpretations.  Assumptions can be critical to helping clarify understanding between requestor and responder.
We kindly request that the TO RFQ be revised to allow for assumptions with Contractor quotes so that any necessary clarifications may be provided along with pricing.

**Comment by randyhart** [comment]
The RFQ is not going to be changed. One of the objectives of the Agile BPA is finding new ways of contracting for the delivery of code.  The idea is to have a collaborative approach between the vendor, 18F, and the product owner in order to deliver working code.  Relying on written assumptions instead of collaboratively working through "blockers" as part of the agile sprint process is counter to this objective.
